### ISSUE TITLE
Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by Loonz206** [ajbogh/node-image-farmer#2]
Currently running **Node** v5.4.1 **npm** 3.3.12 OSX Yosemite 

Error message shows when running npm install on Mac OSX system after cloning the project.
Following message shows. 
_Make sure you have the latest version of node.js and npm installed._
Then the Failed at Canvas install script 'node-gyp rebuild'

You can get their info via:
npm owner ls canvas

After running this I get several email addresses with 
tjholowaychuk <tj@vision-media.ca>
kangax <kangax@gmail.com>
tootallnate <nathan@tootallnate.net>
rauchg <rauchg@gmail.com>
domenic <d@domenic.me>
linusu <linus@folkdatorn.se>

**Comment by ajbogh** [comment]
I adjusted the mac installation code to handle when xcode-select is already installed. You can download master or the 1.2.8 tag and run 'npm run install-mac-deps', then run 'npm install' again.

**Comment by Loonz206** [comment]
Going to comment on this for technical tracking. I am creating a PR on this branch with the updated solutions for adding the path to the .bash_profile to solve for issues.

**Comment by ajbogh** [comment]
See PR#3.
